### ISSUE TITLE
SQL Injection Attack on Bad SearchEmployees

### ISSUE THREAD

**Issue by andey-robins** [clockwise-software/copper#4]
**Describe the bug**
SQL Injection attack possible on Search

**To Reproduce**
1. Go to 'Bad SearchEmployees'
2. Enter in `' OR lastname != '` as the query
3. Press submit
4. See the full queried list, demonstrating arbitrary SQL injection

**Expected behavior**
This should not be possible, so any user inputs need to be sanitized/escaped

**Screenshots**
Query: ![Query](https://user-images.githubusercontent.com/43155608/112730924-eb437680-8ef9-11eb-96b7-2492488a1c91.png)

Results: ![Results](https://user-images.githubusercontent.com/43155608/112730937-f8606580-8ef9-11eb-81ea-b7fac3121c54.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20
 - Browser: Firefox
 - Version: 87
 - **NOTE: This is an architecture problem, but information is still provided for completeness**

**Comment by TheAntonverse** [comment]
We need to fix the 'sql_string =' line in #18 to prevent injection for SearchEmployee.
